#!/bin/sh
set -e

purge_mapper_lock() {
    rm -f \
        /run/lock/tedge-mapper-c8y.lock \
        /run/lock/tedge-mapper-az.lock \
        /run/lock/tedge-mapper-aws.lock \
        /run/lock/tedge-mapper-collectd.lock
}

case "$1" in
    purge)
        purge_mapper_lock
    ;;
esac

# Automatically added by thin-edge.io
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ "$1" = "remove" ]; then
	if command -v deb-systemd-helper >/dev/null 2>&1; then
		deb-systemd-helper mask tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service tedge-mapper-aws.target tedge-mapper-az.target tedge-mapper-c8y.target >/dev/null || true
	elif command -v systemctl >/dev/null 2>&1; then
		systemctl mask tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service tedge-mapper-aws.target tedge-mapper-az.target tedge-mapper-c8y.target >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if command -v deb-systemd-helper >/dev/null 2>&1; then
		deb-systemd-helper purge tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service tedge-mapper-aws.target tedge-mapper-az.target tedge-mapper-c8y.target >/dev/null || true
		deb-systemd-helper unmask tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service tedge-mapper-aws.target tedge-mapper-az.target tedge-mapper-c8y.target >/dev/null || true
	elif command -v systemctl >/dev/null 2>&1; then
		systemctl unmask tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service tedge-mapper-aws.target tedge-mapper-az.target tedge-mapper-c8y.target >/dev/null || true
	fi
fi
# End automatically added section
