#!/bin/sh
set -e
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-collectd.service tedge-mapper-aws.target tedge-mapper-az.target tedge-mapper-c8y.target >/dev/null || true
fi
# End automatically added section