package tedge:filter;

world tedge {
    type timestamp = string;

    record message {
        topic: string,
        payload: string,
    }

    variant filter-error {
        unsupported-message(string),
        incorrect-setting(string),
    }

    // Process a single message; producing zero, one or more transformed messages
    export process: func(timestamp: timestamp, message: message) -> result< list<message>, filter-error >;

    // Update the filter configuration
    export update-config: func(config: message) -> result< _, filter-error >;

    // Close the current time-window; producing zero, one or more accumulated messages
    export tick: func(timestamp: timestamp) -> result< list<message>, filter-error >;
}
