#!/bin/sh
set -e

remove_user_tedge() {
    if getent passwd tedge > /dev/null; then
        deluser --quiet --system tedge
    fi
}

remove_tedge_users_group() {
    if getent group tedge-users > /dev/null; then
        groupdel tedge-users
    fi
}

remove_sudoers_file() {
    if [ -f "/etc/sudoers.d/tedge-users" ]; then
        rm /etc/sudoers.d/tedge-users
    fi

    if [ -f "/etc/sudoers.d/tedge-users-nopasswd" ]; then
        rm /etc/sudoers.d/tedge-users-nopasswd
    fi
}

purge_configs() {
    if [ -d "/etc/tedge" ]; then
        rm -rf /etc/tedge
    fi
}

remove_mosquitto_edit() {
    if [ -f "/etc/mosquitto/mosquitto.conf" ]; then
        sed -i '/include_dir \/etc\/tedge\/mosquitto-conf/d' /etc/mosquitto/mosquitto.conf
    fi
}

purge_var_log() {
    if [ -d "/var/log/tedge" ]; then
        rm -rf /var/log/tedge
    fi
}

case "$1" in
    purge)
        remove_user_tedge
        remove_tedge_users_group
        remove_mosquitto_edit
        remove_sudoers_file
        purge_configs
        purge_var_log
    ;;

    remove)
        remove_user_tedge
        remove_tedge_users_group
        remove_mosquitto_edit
        remove_sudoers_file
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "tedge postrm called with unknown argument \`$1\`" >&2
        exit 1
    ;;
esac

#DEBHELPER#
