#!/bin/sh
set -e

command_exists() {
    command -V "$1" >/dev/null 2>&1
}

remove_user_tedge() {
    if getent passwd tedge > /dev/null; then
        if command_exists userdel; then
            userdel tedge
        elif command_exists deluser; then
            deluser tedge
        else
            echo "WARNING: Could not delete group: tedge" >&2
        fi
    fi
}

remove_tedge_group() {
    if getent group tedge > /dev/null; then
        if command_exists groupdel; then
            groupdel tedge
        elif command_exists delgroup; then
            delgroup tedge
        else
            echo "WARNING: Could not delete group: tedge" >&2
        fi
    fi
}

remove_sudoers_file() {
    if [ -f "/etc/sudoers.d/tedge" ]; then
        rm /etc/sudoers.d/tedge
    fi

    if [ -f "/etc/sudoers.d/tedge-nopasswd" ]; then
        rm /etc/sudoers.d/tedge-nopasswd
    fi
}

purge_configs() {
    if [ -d "/etc/tedge" ]; then
        rm -rf /etc/tedge
    fi
}

remove_mosquitto_edit() {
    if [ -f "/etc/mosquitto/mosquitto.conf" ]; then
        sed -i '/include_dir \/etc\/tedge\/mosquitto-conf/d' /etc/mosquitto/mosquitto.conf
    fi
}

purge_var_log() {
    if [ -d "/var/log/tedge" ]; then
        rm -rf /var/log/tedge
    fi
}

case "$1" in
    purge)
        remove_user_tedge
        remove_tedge_group
        remove_mosquitto_edit
        remove_sudoers_file
        purge_configs
        purge_var_log
    ;;
esac

#DEBHELPER#
