#!/bin/sh
set -e

# Deprecate: Remove line in 1.x release
# Prevent purge from deleting files related to the package
rm -f /var/lib/dpkg/info/tedge_agent.postrm

# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-agent.service || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	systemctl start tedge-agent.service >/dev/null || true
fi
# End automatically added section
