#!/bin/sh

####################################################################################
### docker-compose plugin is currently a PROTOTYPE and not officially maintained ###
####################################################################################

# Expected signature example: $sudo ./tedge_docker_compose_plugin.sh remove nextcloud-postgres
# File should be downloaded to /tmp/
usage() {
    cat << EOF
USAGE:
    compose <SUBCOMMAND>

SUBCOMMANDS:
    list           List all the installed modules
    prepare        Prepare a sequences of install/remove commands
    install        Install a module (install expects docker-compose file to be under "/tmp/")
    remove         Uninstall a module 
    finalize       Removes unused images
EOF
}

DOCKER_COMPOSE_PLUGIN_PATH="/etc/tedge/sm-plugins/docker-compose/"
TMP_PATH="/tmp/"

unsupported_args_check() {
    if ! [ -z $1 ]; then
        echo "Unsupported arguments: $@"
        exit 1
    fi
}

extract_docker_compose_name_from_args() {
    COMPOSE_ARG="$1"
    if [ -z "$COMPOSE_ARG" ]; then
        echo "docker-compose.yaml path is a mandatory argument"
        exit 1
    fi
    shift   # Pop image name from args list
     COMPOSE_NAME=$COMPOSE_ARG
}

if [ -z $1 ]; then
    echo "Provide at least one subcommand\n"
    usage
    exit 1
fi

COMMAND="$1"
shift   # Pop the command from args list

case "$COMMAND" in
    prepare)
        # nothing to do here
        ;;
    list)
	# Reporting with version 1 for each line for now, will be remove when tab at end of line is not mandatory anymore.
        ls $DOCKER_COMPOSE_PLUGIN_PATH | sed $'s/$/\t1/'  || exit 2
        ;;
    install)
        # Extract the docker docker-compose path into the COMPOSE_NAME variable
        extract_docker_compose_name_from_args $@
        TMP_PATH="$TMP_PATH$COMPOSE_NAME"
        #echo $TMP_PATH

        if [ -f "$TMP_PATH" ]; then
            echo "Starting docker-compose file $TMP_PATH"
            # Copy docker-compose file to plugin folder to store it ther until removal
            sudo cp $TMP_PATH $DOCKER_COMPOSE_PLUGIN_PATH
            #COMPOSE_NAME="$(echo $TMP_PATH | cut -d/ -f3 | cut -d. -f1)"
            INSTALL_PATH="$DOCKER_COMPOSE_PLUGIN_PATH$COMPOSE_NAME"

            # Spawn new containers with the provided image name and version to replace the stopped one
            sudo docker-compose -f $INSTALL_PATH up -d || exit 2
        else
            echo "File $TMP_PATH not found, make sure to use a working link or file uploaded to make the file available"
        fi
        ;;
    remove)
        # Extract the docker docker-compose path into the  COMPOSE_NAME variable
        extract_docker_compose_name_from_args $@
        REMOVE_PATH="$DOCKER_COMPOSE_PLUGIN_PATH$COMPOSE_NAME"
        echo $REMOVE_PATH
    
        sudo docker-compose -f $REMOVE_PATH down || exit 2
        
        sudo rm $REMOVE_PATH
        ;;
    finalize)
        unsupported_args_check $@
        # Prune all the unused images. The --force command is used to avoid a [y/N] user prompt
        docker image prune --all --force || exit 2
        ;;
    update-list)
        echo "update-list is not supported by compose plugin"
        exit 1
        ;;
    *)
        echo "Unsupported command: $COMMAND . Ignoring it"
        #exit 1
        ;;
esac
