#!/bin/sh
set -e
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop c8y-configuration-plugin.service >/dev/null || true
fi
# End automatically added section
