#!/bin/sh

set -e

### Create supported operation files
c8y-firmware-plugin --init

#DEBHELPER#

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    ### Enable the services if the device is connected to c8y cloud
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ]; then
        systemctl start c8y-firmware-plugin.service
        systemctl enable c8y-firmware-plugin.service
    fi
fi
