#!/bin/bash
case "$1" in
    "list")
        echo "fake_log"
        ;;
    "get")
        case "$2" in
            "fake_log")
                echo "Fake content"
                ;;
            *)
                # Simulate no logs found for unknown types
                echo "No logs found for log type \"$2\"" >&2
                exit 1
                ;;
        esac
        ;;
    *)
        exit 1
        ;;
esac
