#!/bin/sh
set -e

# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-aws.service || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-az.service || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-c8y.service || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-local.service || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-collectd.service || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-aws.target || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-az.target || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 1 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Initial installation
    /usr/lib/systemd/systemd-update-helper install-system-units tedge-mapper-c8y.target || :
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ $1 -eq 2 ]; then
		_dh_action=restart
	else
		_dh_action=start
	fi
	systemctl $_dh_action tedge-mapper-aws.target tedge-mapper-az.target tedge-mapper-c8y.target >/dev/null || true
fi
# End automatically added section
# Automatically added by thin-edge.io
if [ $1 -eq 2 ]; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		systemctl restart tedge-mapper-aws.service tedge-mapper-az.service tedge-mapper-c8y.service tedge-mapper-local.service tedge-mapper-collectd.service >/dev/null || true
	fi
fi
# End automatically added section

enable_start_service() {
    name="$1"

    if command -v deb-systemd-helper >/dev/null 2>&1; then
        deb-systemd-helper enable "$name" >/dev/null || true
    else
        systemctl enable "$name" >/dev/null || true
    fi

    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true

        if command -v deb-systemd-invoke >/dev/null 2>&1; then
            deb-systemd-invoke start "$name" >/dev/null || true
        else
            systemctl start "$name" >/dev/null || true
        fi
    fi
}

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    ### Enable the service if the device is connected to c8y cloud
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ]; then
        enable_start_service tedge-mapper-c8y.service
    fi
    ### Enable the service if the device is connected to az cloud
    if [ -f "/etc/tedge/mosquitto-conf/az-bridge.conf" ]; then
        enable_start_service tedge-mapper-az.service
    fi
    ### Enable the service if the device is connected to aws cloud
    if [ -f "/etc/tedge/mosquitto-conf/aws-bridge.conf" ]; then
        enable_start_service tedge-mapper-aws.service
    fi
    if [ -d /run/systemd/system ]; then
        ### Enable the service if the collectd is running on the device
        if systemctl is-active --quiet collectd.service; then
            enable_start_service tedge-mapper-collectd.service
        fi
    fi
fi

if [ -f /var/lib/dpkg/info/tedge_mapper.postrm ]; then
    # Prevent purge from deleting files related to the package
    rm -f /var/lib/dpkg/info/tedge_mapper.postrm
fi
