#!/bin/sh

set -e

# Deprecate: Remove symlink in 1.x release
if [ ! -e /usr/bin/tedge_mapper ]; then
    ln -s /usr/bin/tedge-mapper /usr/bin/tedge_mapper
fi

#DEBHELPER#

enable_start_service() {
    name="$1"
    deb-systemd-helper enable "$name" >/dev/null || true
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
        deb-systemd-invoke start "$name" >/dev/null || true
    fi
}

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    ### Enable the service if the device is connected to c8y cloud
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ]; then
        enable_start_service tedge-mapper-c8y.service
    fi
    ### Enable the service if the device is connected to az cloud
    if [ -f "/etc/tedge/mosquitto-conf/az-bridge.conf" ]; then
        enable_start_service tedge-mapper-az.service
    fi
    ### Enable the service if the device is connected to aws cloud
    if [ -f "/etc/tedge/mosquitto-conf/aws-bridge.conf" ]; then
        enable_start_service tedge-mapper-aws.service
    fi
    ### Enable the service if the collectd is running on the device
    if systemctl is-active --quiet collectd.service; then
        enable_start_service tedge-mapper-collectd.service
    fi
fi

if [ -f /var/lib/dpkg/info/tedge_mapper.postrm ]; then
    # Prevent purge from deleting files related to the package
    rm -f /var/lib/dpkg/info/tedge_mapper.postrm
fi
