#!/bin/sh

set -e

# Deprecate: Remove symlink in 1.x release
if [ ! -e /usr/bin/c8y_configuration_plugin ]; then
    ln -s /usr/bin/c8y-configuration-plugin /usr/bin/c8y_configuration_plugin
fi

#DEBHELPER#
