#!/bin/sh

set -e

### Create supported operation files
c8y-configuration-plugin --init

# Deprecate: Remove symlink in 1.x release
if [ ! -e /usr/bin/c8y_configuration_plugin ]; then
    ln -s /usr/bin/c8y-configuration-plugin /usr/bin/c8y_configuration_plugin
fi

#DEBHELPER#

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    ### Enable the services if the device is connected to c8y cloud
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ]; then
        systemctl start c8y-configuration-plugin.service
        systemctl enable c8y-configuration-plugin.service
    fi
fi
