#!/bin/sh

set -e

# Stop the service only if systemctl is available
if command -v systemctl >/dev/null; then
    if systemctl is-active --quiet c8y-configuration-plugin.service; then
         systemctl stop c8y-configuration-plugin.service
    fi
fi

if [ -e /usr/bin/c8y_configuration_plugin ]; then
    rm -f /usr/bin/c8y_configuration_plugin
fi

#DEBHELPER#
