#!/bin/bash
set -eu

case "$1" in
    "list")
        echo "dummy_config"
        ;;
    "get")
        case "$2" in
            "dummy_config")
                echo "Dummy content"
                ;;
            *)
                echo "Unsupported config type \"$2\"" >&2
                exit 1
                ;;
        esac
        ;;
    "prepare")
        case "$2" in
            "dummy_config")
                echo "Dummy prepare"
                ;;
            *)
                echo "Unsupported config type \"$2\"" >&2
                exit 1
                ;;
        esac
        ;;
    "set")
        case "$2" in
            "dummy_config")
                echo "Config updated successfully"
                ;;
            *)
                echo "Unsupported config type \"$2\"" >&2
                exit 1
                ;;
        esac
        ;;
    "verify")
        case "$2" in
            "dummy_config")
                echo "Dummy verify"
                ;;
            *)
                echo "Unsupported config type \"$2\"" >&2
                exit 1
                ;;
        esac
        ;;
    "rollback")
        case "$2" in
            "dummy_config")
                echo "Dummy rollback"
                ;;
            *)
                echo "Unsupported config type \"$2\"" >&2
                exit 1
                ;;
        esac
        ;;
    *)
        exit 1
        ;;
esac
