#!/bin/sh

set -e

# Deprecate: Remove symlink in 1.x release
if [ ! -e /usr/bin/tedge_watchdog ]; then
    ln -s /usr/bin/tedge-watchdog /usr/bin/tedge_watchdog
fi

#DEBHELPER#

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    systemctl start tedge-watchdog.service
    systemctl enable tedge-watchdog.service
fi
