#!/bin/sh

set -e

# Stop the service only if systemctl is available
if command -v systemctl >/dev/null; then
    if systemctl is-active --quiet tedge-watchdog.service; then
         systemctl stop tedge-watchdog.service
    fi
fi

# Deprecate: Remove symlink in 1.x release
if [ -e /usr/bin/tedge_watchdog ]; then
    rm -f /usr/bin/tedge_watchdog
fi

#DEBHELPER#
