#!/bin/sh
set -e
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	if command -v deb-systemd-invoke >/dev/null 2>&1; then
		deb-systemd-invoke stop tedge-p11-server.socket >/dev/null || true
	else
		systemctl stop tedge-p11-server.socket >/dev/null || true
	fi
fi
# End automatically added section