#!/bin/sh
# detect if a HSM is available to be used and configure it

shift # phase

HSM_TYPE=${HSM_TYPE:-}

# Set module defaults
detect_hsm() {
    FOUND_MODULE=$(find /usr/lib -name libtpm2_pkcs11.so | head -n1)
    if [ -n "$FOUND_MODULE" ]; then
        HSM_TYPE=tpm2
        return 0
    fi

    FOUND_MODULE=$(find /usr/lib -name opensc-pkcs11.so | head -n1)
    if [ -n "$FOUND_MODULE" ]; then
        HSM_TYPE=nitrokey
        return 0
    fi

    FOUND_MODULE=$(find /usr/lib -name libsofthsm2.so | head -n1)
    if [ -n "$FOUND_MODULE" ]; then
        HSM_TYPE=softhsm2
        return 0
    fi
    return 1
}

# an explicit HSM_TYPE skips the detection
[ -n "$HSM_TYPE" ] || detect_hsm ||:
if [ -z "$HSM_TYPE" ]; then
    echo "Could not find a hsm on the device" >&2
    exit 2
fi

tedge-init-hsm.sh --type "$HSM_TYPE"
