#!/bin/sh

set -e

# Stop the service only if systemctl is available
if command -v systemctl >/dev/null; then
    if systemctl is-active --quiet c8y-firmware-plugin.service; then
         systemctl stop c8y-firmware-plugin.service
    fi
fi

# Automatically added by cargo-deb
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop c8y-firmware-plugin.service >/dev/null || true
fi
# End automatically added section

