#!/bin/sh
set -e

# Automatically added by thin-edge.io
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	if command -v deb-systemd-invoke >/dev/null 2>&1; then
		deb-systemd-invoke stop c8y-remote-access-plugin.socket >/dev/null || true
	else
		systemctl stop c8y-remote-access-plugin.socket >/dev/null || true
	fi
fi
# End automatically added section

### Remove supported operation files
c8y-remote-access-plugin --cleanup
