#!/bin/sh
set -e

# Automatically added by thin-edge.io
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop c8y-remote-access-plugin.socket >/dev/null || true
fi
# End automatically added section

### Remove supported operation files
c8y-remote-access-plugin --cleanup
