#!/bin/sh
set -e

purge_agent_directory() {
    if [ -d "/etc/tedge/.agent" ]; then
        rm -rf /etc/tedge/.agent
    fi
}

purge_agent_lock() {
   if [ -f "/run/lock/tedge_agent.lock" ]; then
       rm -rf /run/lock/tedge_agent.lock
   fi
}

purge_var_data_directory() {
    if [ -d "/var/tedge" ]; then
        rm -rf /var/tedge
    fi
}

case "$1" in
    purge)
       purge_agent_directory
       purge_agent_lock
       purge_var_data_directory
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "tedge postrm called with unknown argument \`$1\`" >&2
        exit 1
    ;;
esac

#DEBHELPER#
