//! Helpers called by `define_config!`-generated reader `build` methods.

use std::borrow::Cow;
use std::str::FromStr;

use facet::Facet;

use crate::defaults::config_resolve;
use crate::defaults::DefaultSpec;
use crate::defaults::DefaultsRegistry;
use crate::defaults::ResolvedValue;
use crate::defaults::RootResolver;
use crate::reflect::ConfigError;
use crate::OptionalConfig;

/// Reads a required field (one with a concrete default) from the DTO, parsing it from its string representation
pub fn read_required<T: FromStr>(
    dto: &impl for<'a> Facet<'a>,
    defaults: &DefaultsRegistry,
    root_resolver: RootResolver<'_>,
    key: &str,
) -> Result<T, ConfigError>
where
    T::Err: std::fmt::Display,
{
    let resolved = config_resolve(dto, key, defaults, root_resolver)?
        .unwrap_or_else(|| panic!("Required config key '{key}' is not set and has no default"));
    parse_resolved(key, resolved)
}

/// Parses a resolved value into the field's type, reporting where a bad value came from
fn parse_resolved<T: FromStr>(key: &str, resolved: ResolvedValue) -> Result<T, ConfigError>
where
    T::Err: std::fmt::Display,
{
    let ResolvedValue {
        value,
        source_key,
        origin,
    } = resolved;
    value
        .parse()
        .map_err(|e: T::Err| ConfigError::InvalidValue {
            key: key.to_owned(),
            source_key,
            origin,
            reason: e.to_string(),
            value,
        })
}

/// Reads an optional field (no guaranteed default) into an `OptionalConfig`
pub fn read_optional<T: FromStr>(
    dto: &impl for<'a> Facet<'a>,
    defaults: &DefaultsRegistry,
    root_resolver: RootResolver<'_>,
    key: &str,
    display_prefix: &str,
    profile: Option<&str>,
) -> Result<OptionalConfig<T>, ConfigError>
where
    T::Err: std::fmt::Display,
{
    let resolved = config_resolve(dto, key, defaults, root_resolver)?;

    let profile_value = profile.map(str::to_owned);

    match resolved {
        Some(resolved) => {
            let display_key = dotted_key(display_prefix, key);
            let parsed: T = parse_resolved(key, resolved)?;
            Ok(OptionalConfig::present(parsed, display_key).with_profile(profile_value))
        }
        None => {
            let presentation = presentation_key(defaults, key);
            let display_key = dotted_key(display_prefix, presentation);
            Ok(OptionalConfig::empty(display_key).with_profile(profile_value))
        }
    }
}

fn presentation_key<'a>(defaults: &'a DefaultsRegistry, mut key: &'a str) -> &'a str {
    for _ in 0..10 {
        match defaults.get(key) {
            Some(DefaultSpec::FromOptionalKey(source)) => key = source,
            _ => break,
        }
    }
    key
}

/// Prefixes a schema-relative key with the path where its schema is mounted
///
/// A reader generated by `define_config!` names its fields relative to its own
/// schema root. When that schema is embedded elsewhere with `extern`, the
/// embedding config passes the mount path so DTO lookups and defaults resolve
/// under the prefixed key.
pub fn key_at<'a>(prefix: &str, key: &'a str) -> Cow<'a, str> {
    if prefix.is_empty() {
        Cow::Borrowed(key)
    } else {
        Cow::Owned(format!("{prefix}.{key}"))
    }
}

fn dotted_key(prefix: &str, key: &str) -> String {
    key_at(prefix, key).into_owned()
}
