//! Checks that a schema's own declarations are usable.
//!
//! Defaults and examples are declared as strings and only parsed into the
//! field's type when a reader is built, so a `default(value = "188x")` on a
//! `u16` field compiles happily and fails at runtime. [check_schema] exercises
//! every declaration against the real parse path, and `define_config!` calls it
//! from a generated `#[test]` so the failure lands at build time instead.

use std::fmt::Display;
use std::path::Path;

use crate::manager::ConfigManager;
use crate::reader::BuildFromDto;
use crate::reflect::ConfigError;
use crate::schema::ConfigSchema;

/// Everything wrong with a schema's defaults and examples
#[derive(Debug, PartialEq, Eq)]
pub struct SchemaProblems {
    problems: Vec<String>,
}

impl SchemaProblems {
    /// The individual problems, in the order they were found
    pub fn problems(&self) -> &[String] {
        &self.problems
    }
}

impl Display for SchemaProblems {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "invalid schema:")?;
        for problem in &self.problems {
            writeln!(f, "  {problem}")?;
        }
        Ok(())
    }
}

impl std::error::Error for SchemaProblems {}

/// Checks that every default and example a schema declares is a valid value
/// for the field it belongs to
///
/// `C` is the reader type generated by `define_config!`. Reports every problem
/// it finds rather than stopping at the first, so one run lists all of them.
///
/// Keys whose default falls back to the root config are skipped: `from_root`
/// cannot resolve without a mounted root config, which is a property of how the
/// schema is used rather than of the schema itself.
pub fn check_schema<C: ConfigSchema + BuildFromDto>(
    config_dir: &Path,
) -> Result<(), SchemaProblems> {
    let manager = ConfigManager::from_schema::<C>(config_dir);
    let unset = C::Dto::default();
    let mut problems = Vec::new();

    for entry in manager.key_entries::<C::Dto>() {
        for example in entry.examples {
            let mut dto = C::Dto::default();
            if let Err(e) = manager.set(&mut dto, &entry.key, example) {
                problems.push(format!(
                    "{}: example '{example}' is not a valid value: {}",
                    entry.key,
                    parse_reason(e)
                ));
            }
        }

        match manager.resolve(&unset, &entry.key) {
            // A default that resolves must also be a valid value for the field.
            // Reporting it through the resolved provenance gives the same
            // message the reader would, naming where the value came from.
            Ok(Some(resolved)) => {
                let mut dto = C::Dto::default();
                if let Err(e) = manager.set(&mut dto, &entry.key, &resolved.value) {
                    problems.push(
                        ConfigError::InvalidValue {
                            key: entry.key.clone(),
                            source_key: resolved.source_key,
                            origin: resolved.origin,
                            value: resolved.value,
                            reason: parse_reason(e),
                        }
                        .to_string(),
                    );
                }
            }
            // Unset with no default, or an optional fallback to an unset key
            Ok(None) => {}
            Err(ConfigError::NoRootConfig { .. }) => {}
            Err(e) => problems.push(format!("{}: default cannot be resolved: {e}", entry.key)),
        }
    }

    // A backstop for whatever the per-key checks cannot see, such as a
    // required key that resolves to nothing. It stops at the first bad field,
    // so it only adds noise once a per-key check has already found something.
    if problems.is_empty() && manager.root_dependencies().is_empty() {
        if let Err(e) = manager.build_reader::<_, C>(&unset, None, "", None) {
            problems.push(format!("the reader cannot be built from defaults: {e}"));
        }
    }

    if problems.is_empty() {
        Ok(())
    } else {
        Err(SchemaProblems { problems })
    }
}

/// Unwraps the reason a value failed to parse, so it can be re-reported
/// against the key's provenance rather than nested inside another message
fn parse_reason(error: ConfigError) -> String {
    match error {
        ConfigError::ParseError(reason) => reason,
        other => other.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn problems_are_listed_one_per_line() {
        let problems = SchemaProblems {
            problems: vec!["mqtt.port: bad".into(), "c8y.url: worse".into()],
        };

        assert_eq!(
            problems.to_string(),
            "invalid schema:\n  mqtt.port: bad\n  c8y.url: worse\n"
        );
    }
}
