#!/bin/sh

set -e

purge_agent_directory() {
    if [ -d "/etc/tedge/.agent" ]; then
        rm -rf /etc/tedge/.agent
    fi
}

purge_agent_lock() {
    # remove old lock file path
    if [ -f "/run/lock/tedge_agent.lock" ]; then
        rm -rf /run/lock/tedge_agent.lock
    fi
    
    if [ -f "/run/lock/tedge-agent.lock" ]; then
        rm -rf /run/lock/tedge-agent.lock
    fi
}

purge_agent_logs() {
    if [ -d "/var/log/tedge/agent" ]; then
        rm -rf /var/log/tedge/agent
    fi
}

purge_var_data_directory() {
    if [ -d "/var/tedge" ]; then
        rm -rf /var/tedge
    fi
}

case "$1" in
    purge)
       purge_agent_directory
       purge_agent_lock
       purge_var_data_directory
       purge_agent_logs
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "tedge postrm called with unknown argument \`$1\`" >&2
        exit 1
    ;;
esac

if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper mask tedge-agent.service >/dev/null || true
        fi
fi

if [ "$1" = "purge" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge tedge-agent.service >/dev/null || true
                deb-systemd-helper unmask tedge-agent.service >/dev/null || true
        fi
fi

# Do not use DEBHELPER: for OTA self-update one needs a fine-control over the deb options
