#!/bin/sh

set -e

# Deprecate: Remove symlink in 1.x release
if [ ! -e /usr/bin/tedge_agent ]; then
    ln -s /usr/bin/tedge-agent /usr/bin/tedge_agent
fi

# Initialize the agent __only__ if not when agent is running.
# Indeed, during an OTA self-update, the previous version of the  `agent` is kept running
# to monitor the installation of the new version up to completion.
if command -v systemctl >/dev/null; then
    if ! systemctl is-active --quiet tedge-agent ; then
         # Flock file should be removed as `tedge-agent --init` must run as root
         # although the flockfile is owned by `tedge`.
         if [ -f "/run/lock/tedge_agent.lock" ]; then
                rm /run/lock/tedge_agent.lock
         fi

         if [ -f "/run/lock/tedge-agent.lock" ]; then
                rm /run/lock/tedge-agent.lock
         fi
         # It must be run as root to create the directory `/var/tedge`.
         tedge-agent --init
    fi
fi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
        if deb-systemd-helper debian-installed tedge-agent.service; then
                # This will only remove masks created by d-s-h on package removal.
                deb-systemd-helper unmask tedge-agent.service >/dev/null || true

                if deb-systemd-helper --quiet was-enabled tedge-agent.service; then
                        # Create new symlinks, if any.
                        deb-systemd-helper enable tedge-agent.service >/dev/null || true
                fi
        fi

        # Update the statefile to add new symlinks (if any), which need to be cleaned
        # up on purge. Also remove old symlinks.
        deb-systemd-helper update-state tedge-agent.service >/dev/null || true
fi

# Enable the services only if systemctl is available
if command -v systemctl >/dev/null; then
    # Start the agent __only__ if not already running.
    # Indeed, during an OTA self-update, the previous version of the  `agent` is kept running
    # to monitor the installation of the new version up to completion.
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ] && ! systemctl is-active --quiet tedge-agent ; then
        systemctl start tedge-agent.service
        systemctl enable tedge-agent.service
    fi
fi

if [ -f /var/lib/dpkg/info/tedge_agent.postrm ]; then
    # Prevent purge from deleting files related to the package
    rm -f /var/lib/dpkg/info/tedge_agent.postrm
fi

# Do not use DEBHELPER: for OTA self-update one needs a fine-control over the deb options
