#!/bin/sh
set -e

purge_mapper_lock() {
    rm -f \
        /run/lock/tedge-mapper-c8y.lock \
        /run/lock/tedge-mapper-az.lock \
        /run/lock/tedge-mapper-aws.lock \
        /run/lock/tedge-mapper-collectd.lock
}

case "$1" in
    purge)
        purge_mapper_lock
    ;;
esac


