#!/bin/sh
set -e

# Automatically added by thin-edge.io
if [ $1 -eq 0 ] && [ -x "/usr/lib/systemd/systemd-update-helper" ]; then
    # Package removal, not upgrade
    /usr/lib/systemd/systemd-update-helper remove-system-units c8y-remote-access-plugin.socket || :
fi
# End automatically added section

### Remove supported operation files
c8y-remote-access-plugin --cleanup
