#!/bin/sh

set -e

# Stop the service only if systemctl is available
if command -v systemctl >/dev/null; then
    if systemctl is-active --quiet c8y-configuration-plugin.service; then
         systemctl stop c8y-configuration-plugin.service
    fi
fi

#DEBHELPER#
