{{- if .Values.persistence.createPv }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tedge.persistence.pvName" . | quote }}
  labels:
    storage: "tedge"
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  hostPath:
    path: {{ include "tedge.persistence.hostPath" . | quote }}
    type: DirectoryOrCreate
{{- end }}

{{- if .Values.persistence.createClaim }}
{{- if .Values.persistence.createPv }}
---
{{- end }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tedge.persistence.claimName" . | quote }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}

{{- if and (eq .Values.certs.source "pvc") .Values.certs.createPv }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tedge.certs.pvName" . | quote }}
  labels:
    storage: "tedge-certs"
spec:
  capacity:
    storage: {{ .Values.certs.size }}
  accessModes:
    - {{ .Values.certs.accessMode }}
  hostPath:
    path: {{ include "tedge.certs.hostPath" . | quote }}
    type: DirectoryOrCreate
{{- end }}

{{- if and (eq .Values.certs.source "pvc") .Values.certs.createClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tedge.certs.claimName" . | quote }}
spec:
  accessModes:
    - {{ .Values.certs.accessMode }}
  resources:
    requests:
      storage: {{ .Values.certs.size }}
{{- end }}

{{- if .Values.mosquitto.persistence.createPv }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "tedge.mosquitto.pvName" . | quote }}
  labels:
    storage: "tedge-mosquitto"
spec:
  capacity:
    storage: {{ .Values.mosquitto.persistence.size }}
  accessModes:
    - {{ .Values.mosquitto.persistence.accessMode }}
  hostPath:
    path: {{ include "tedge.mosquitto.hostPath" . | quote }}
    type: DirectoryOrCreate
{{- end }}

{{- if .Values.mosquitto.persistence.createClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tedge.mosquitto.claimName" . | quote }}
spec:
  accessModes:
    - {{ .Values.mosquitto.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.mosquitto.persistence.size }}
{{- end }}
