#!/bin/sh

set -e

# Create a group "tedge-dm-agent" if not created before
if ! getent group tedge-dm-agent > /dev/null; then
    addgroup --quiet --system tedge-dm-agent
fi

# Create a user "tedge-dm-agent" if not created before
if ! getent passwd tedge-dm-agent > /dev/null; then
    adduser --quiet --system --no-create-home --ingroup tedge-dm-agent --shell /usr/sbin/nologin tedge-dm-agent
fi

#DEBHELPER#
