#!/bin/sh
set -e

# Deprecate: Remove line in 1.x release
# Prevent purge from deleting files related to the package
rm -f /var/lib/dpkg/info/tedge_agent.postrm

# Remove older prerm maintainer scripts which would stop the tedge-agent service during an OTA
rm -f /var/lib/dpkg/info/tedge_agent.prerm


