#!/bin/sh
set -e

# upgrade the config to move out the mapper specific settings from tedge.toml
if ! tedge config upgrade; then
    code="$?"
    echo "WARNING: 'tedge config upgrade' failed. code=$code" >&2
fi

if ! tedge refresh-bridges; then
    # Ignore errors whilst recreating bridges
    # as it can fail if the user has removed settings like c8y.url
    # and not run 'tedge disconnect c8y'
    code="$?"
    echo "WARNING: 'tedge refresh-bridges' failed. code=$code" >&2
fi

#LINUXHELPER#

enable_start_service() {
    name="$1"

    if command -v deb-systemd-helper >/dev/null 2>&1; then
        deb-systemd-helper enable "$name" >/dev/null || true
    else
        systemctl enable "$name" >/dev/null || true
    fi

    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true

        if command -v deb-systemd-invoke >/dev/null 2>&1; then
            deb-systemd-invoke start "$name" >/dev/null || true
        else
            systemctl start "$name" >/dev/null || true
        fi
    fi
}

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    ### Enable the service if the device is connected to c8y cloud
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ]; then
        enable_start_service tedge-mapper-c8y.service
    fi
    ### Enable the service if the device is connected to az cloud
    if [ -f "/etc/tedge/mosquitto-conf/az-bridge.conf" ]; then
        enable_start_service tedge-mapper-az.service
    fi
    ### Enable the service if the device is connected to aws cloud
    if [ -f "/etc/tedge/mosquitto-conf/aws-bridge.conf" ]; then
        enable_start_service tedge-mapper-aws.service
    fi
fi

if [ -f /var/lib/dpkg/info/tedge_mapper.postrm ]; then
    # Prevent purge from deleting files related to the package
    rm -f /var/lib/dpkg/info/tedge_mapper.postrm
fi
