#!/bin/sh
set -e
# Automatically added by thin-edge.io
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop tedge-configuration-plugin.service >/dev/null || true
fi
# End automatically added section