#!/bin/sh

set -e

### Create a group "tedge-mapper" if not created before
if ! getent group tedge-mapper >/dev/null; then
    addgroup --quiet --system tedge-mapper
fi

### Create a user "tedge-mapper" if not created before
# Create user tedge-mapper with no home(--no-create-home), no login(--shell) and in group tedge(--ingroup)
if ! getent passwd tedge-mapper >/dev/null; then
    adduser --quiet --system --no-create-home --ingroup tedge-mapper --shell /usr/sbin/nologin tedge-mapper
fi

### Create operation file.
# This allows thin-edge.io components to list and declare supported operations for the cloud provider.
install -g tedge -o tedge -m 754 -f /etc/tedge/operations/c8y/c8y_SoftwareUpdate

#DEBHELPER#
