#!/bin/sh
set -e

purge_operations() {
    if [ -d "/etc/tedge/operations" ]; then
        rm -rf /etc/tedge/operations
    fi
}

case "$1" in
    purge)
       purge_operations
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "tedge postrm called with unknown argument \`$1\`" >&2
        exit 1
    ;;
esac

#DEBHELPER#
