#!/bin/sh

set -e

### Initialize the mapper
sudo -u tedge -- tedge_mapper --init c8y
sudo -u tedge -- tedge_mapper --init az

#DEBHELPER#

# Enable the service only if systemctl is available
if command -v systemctl >/dev/null; then
    ### Enable the service if the device is connected to c8y cloud
    if [ -f "/etc/tedge/mosquitto-conf/c8y-bridge.conf" ]; then
        systemctl start tedge-mapper-c8y.service
        systemctl enable tedge-mapper-c8y.service
    fi
    ### Enable the service if the device is connected to az cloud
    if [ -f "/etc/tedge/mosquitto-conf/az-bridge.conf" ]; then
        systemctl start tedge-mapper-az.service
        systemctl enable tedge-mapper-az.service
    fi
    ### Enable the service if the collectd is running on the device
    if systemctl is-active --quiet collectd.service; then
        systemctl start tedge-mapper-collectd.service
    fi
fi
