#!/bin/sh
set -e

### Remove user tedge-mapper
if getent passwd tedge-mapper >/dev/null; then
    deluser --quiet --system tedge-mapper
fi

if [ -f "/etc/tedge/operations/c8y/c8y_SoftwareUpdate" ]; then
    rm -rf /etc/tedge/operations/c8y/c8y_SoftwareUpdate
fi

#DEBHELPER#
