#!/bin/sh

set -e

# Stop the services only if systemctl is available
if command -v systemctl >/dev/null; then
    if systemctl is-active --quiet tedge-mapper-c8y; then
        systemctl stop tedge-mapper-c8y.service
    fi

    if systemctl is-active --quiet tedge-mapper-collectd; then
        systemctl stop tedge-mapper-collectd.service
    fi

    if systemctl is-active --quiet tedge-mapper-az; then
        systemctl stop tedge-mapper-az.service
    fi
fi

#DEBHELPER#
